### ISSUE TITLE
Run TermRecord in centos5 Tip invalid command option

### ISSUE THREAD

**Issue by bjjasonzhao** [theonewolf/TermRecord#15]
[root@localhost ~]# TermRecord -o /tmp/session
script: invalid option -- /
usage: script [-a] [-f] [-q] [-t] [file]

**Comment by piter50** [comment]
Was this ever resolved?  I have the same issue, but running Centos 6.4.
I used pip to install TermRecord.  It happens regardless of if I specify a / in my path or not.

**Comment by theonewolf** [comment]
This is because the underlying command `script` is so ancient that its options do not match more modernish versions (even 1 year newer versions).

I think, without harming the fidelity of the capture, we can just always use the old form of `-t` which sends to `stderr` by default and capture that output to the timing file, instead of trying to specify a timing file to `script`.

Version of `script` shipping on my CentOS instance is:

v2.17.2 released in March 2010

version of `script` I developed with:

v 2.20.1 released in October 2011
